name: "Deploy jhkennedy.org"

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: "jhkennedy.org"
          environment-file: conda-env.yml

      - name: Build
        shell: bash -l {0}
        run: lektor build

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          LEKTOR_DEPLOY_USERNAME: ${{ secrets.LEKTOR_DEPLOY_USERNAME }}
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.LEKTOR_DEPLOY_PASSWORD }}
        shell: bash -l {0}
        run: lektor deploy ghpages
